package com.mycompany.projetoarquitetonico.forms;


import com.mycompany.projetoarquitetonico.models.DAO.AccountDAO;
import com.mycompany.projetoarquitetonico.models.entities.Account;
import java.util.List;


/**
 *
 * @author yurit
 */
public class frmAccountFind extends javax.swing.JDialog {
    private String accountType;
    private Account selectedAccount;
    private List<Account> foundAccounts = null;
    

    public frmAccountFind(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.accountType = "";
    }
    
    
    public static Account getAccount(String accountType){
        Account result;
        frmAccountFind frm = new frmAccountFind(null, true);
        frm.setAccountType(accountType);
        frm.setVisible(true);
        
        // returns when frm is not visible
        result = frm.getSelectedAccount();
        frm.dispose();
        return result;
    }

    
    public void setAccountType(String accountType){
        this.accountType = accountType;
    }
    
    
    public Account getSelectedAccount(){
        return this.selectedAccount;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findBy = new javax.swing.ButtonGroup();
        btnSelectAccount = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboAccount = new javax.swing.JComboBox<>();
        txtFoundAccountsCounter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSelectAccount.setText("Selecionar");
        btnSelectAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAccountActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar por Nome ou CPF");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        jLabel3.setText("Contas encontradas");

        txtFoundAccountsCounter.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 222, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectAccount))
                    .addComponent(txtName)
                    .addComponent(comboAccount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFoundAccountsCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFoundAccountsCounter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectAccount)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnSelectAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAccountActionPerformed
        int id = comboAccount.getSelectedIndex();
        
        if( id >= 0 ) this.selectedAccount = this.foundAccounts.get(id);
        else this.selectedAccount = null;
        
        /*
        need this for frmAccountFind.getAccount()
        (returns the selected account when the form is not visible)
        */
        this.setVisible(false);
    }//GEN-LAST:event_btnSelectAccountActionPerformed

    
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    
    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        String search = txtName.getText();
        this.foundAccounts = AccountDAO.findAllByNameOrCPF(search, this.accountType);
        
        comboAccount.removeAllItems();
        if( search.equals("") ){
            txtFoundAccountsCounter.setText("0");
            return;
        }
        
        txtFoundAccountsCounter.setText( String.valueOf( this.foundAccounts.size() ));
        for( Account acc : this.foundAccounts ){
            comboAccount.addItem(acc.getName() + " : " + acc.getCpf());
        }
    }//GEN-LAST:event_txtNameKeyReleased

    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSelectAccount;
    private javax.swing.JComboBox<String> comboAccount;
    private javax.swing.ButtonGroup findBy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtFoundAccountsCounter;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
