package com.mycompany.projetoarquitetonico.forms;


import com.mycompany.projetoarquitetonico.Controllers.LoginController;
import com.mycompany.projetoarquitetonico.utils.BlinkText;
import com.mycompany.projetoarquitetonico.utils.TextMasks;


public class frmLogin extends javax.swing.JFrame {
    /*
    This form has no "controller" attribute, the LoginController uses 
    static methods only.
    */
    
    
    public frmLogin() {
        initComponents();
        lblErrorMessage.setVisible(false);
        
        TextMasks.installCPFMask(txtLogin);
    }

    
    public void showError(String message, String errorType){
        lblErrorMessage.setText(message);
        lblErrorMessage.setVisible(true);
        BlinkText.blinkLabelRed(lblErrorMessage, 3);
        
        switch( errorType ){
            case "cpf" -> BlinkText.blinkTextFieldRed(txtLogin, 3);
            case "password" -> BlinkText.blinkTextFieldRed(txtPassword, 3);
            case "" -> {}
            default -> System.out.println("Unknown error type: " + errorType);
        }
    }
    
    
    public void hideErrorMessage(){
        lblErrorMessage.setVisible(false);
    }
    
    
    public String getLoginText(){
        return txtLogin.getText();
    }
    
    
    public String getPasswordText(){
        return txtPassword.getText();
    }
    
    
    public String getSelectedAccountType(){
        if( radioClient.isSelected() ) return "client";
        if( radioEngineer.isSelected() ) return "engineer";
        if( radioAdmin.isSelected() ) return "admin";
        return null;
    }
    
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupAccountType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        radioClient = new javax.swing.JRadioButton();
        radioEngineer = new javax.swing.JRadioButton();
        radioAdmin = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        lblErrorMessage = new javax.swing.JLabel();
        txtLogin = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Login (CPF)");

        jLabel2.setText("Senha");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnSubmit.setText("Entrar");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        groupAccountType.add(radioClient);
        radioClient.setText("Cliente");
        radioClient.setName("client"); // NOI18N
        radioClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioClientActionPerformed(evt);
            }
        });

        groupAccountType.add(radioEngineer);
        radioEngineer.setText("Engenheiro");
        radioEngineer.setName("engineer"); // NOI18N
        radioEngineer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEngineerActionPerformed(evt);
            }
        });

        groupAccountType.add(radioAdmin);
        radioAdmin.setText("Administrador");
        radioAdmin.setName("admin"); // NOI18N
        radioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAdminActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de conta");

        lblErrorMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorMessage.setText("ERROR_MESSAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(radioClient)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioEngineer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioAdmin))
                        .addComponent(txtPassword)
                        .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioClient)
                    .addComponent(radioEngineer)
                    .addComponent(radioAdmin))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void radioClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioClientActionPerformed
    }//GEN-LAST:event_radioClientActionPerformed

    
    private void radioEngineerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEngineerActionPerformed
    }//GEN-LAST:event_radioEngineerActionPerformed

    
    private void radioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAdminActionPerformed
    }//GEN-LAST:event_radioAdminActionPerformed

    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        LoginController.handleSubmit();
    }//GEN-LAST:event_btnSubmitActionPerformed

    
    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup groupAccountType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioClient;
    private javax.swing.JRadioButton radioEngineer;
    private javax.swing.JFormattedTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
