/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.projetoarquitetonico.forms;

import com.mycompany.projetoarquitetonico.Controllers.TerrainRegistrationController;

/**
 *
 * @author yurit e lincoln
 */


public class frmTerrainRegistration extends javax.swing.JDialog {

    /**
     * Creates new form frmTerrainRegistration
     */
    
    
    public frmTerrainRegistration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        new TerrainRegistrationController(this); // Associar o controlador à view
    }
    // Getters para os componentes da view
    public javax.swing.JButton getBtnRegister() {
        return btnRegister;
    }

    public javax.swing.JButton getBtnClose() {
        return btnClose;
    }

    public javax.swing.JTextField getTxtTerrainName() {
        return txtTerrainName;
    }

    public javax.swing.JTextField getTxtOwnerCPF() {
        return txtOwnerCPF;
    }

    public javax.swing.JTextField getTxtTerrainArea() {
        return txtTerrainArea;
    }

    public javax.swing.JTextField getTxtTerrainLocation() {
        return txtTerrainLocation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTerrainName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOwnerCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTerrainArea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTerrainLocation = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome do terreno");

        txtTerrainName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerrainNameActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF do proprietário");

        txtOwnerCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerCPFActionPerformed(evt);
            }
        });

        jLabel3.setText("Área do terreno");

        txtTerrainArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerrainAreaActionPerformed(evt);
            }
        });

        jLabel4.setText("Localização");

        txtTerrainLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerrainLocationActionPerformed(evt);
            }
        });

        btnRegister.setText("Cadastrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnClose.setText("Fechar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTerrainName)
                    .addComponent(txtOwnerCPF)
                    .addComponent(txtTerrainArea)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTerrainLocation)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 230, Short.MAX_VALUE)
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegister)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTerrainName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOwnerCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTerrainArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTerrainLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOwnerCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerCPFActionPerformed

    private void txtTerrainNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerrainNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerrainNameActionPerformed

    private void txtTerrainAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerrainAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerrainAreaActionPerformed

    private void txtTerrainLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerrainLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerrainLocationActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtOwnerCPF;
    private javax.swing.JTextField txtTerrainArea;
    private javax.swing.JTextField txtTerrainLocation;
    private javax.swing.JTextField txtTerrainName;
    // End of variables declaration//GEN-END:variables
}
