package com.mycompany.projetoarquitetonico.forms;


import com.mycompany.projetoarquitetonico.Controllers.TerrainRegistrationController;
import com.mycompany.projetoarquitetonico.utils.BlinkText;
import com.mycompany.projetoarquitetonico.utils.TextMasks;


/**
 *
 * @author yurit
 */
public class frmTerrainRegistration extends javax.swing.JDialog {
    private final TerrainRegistrationController controller;
    
    
    public frmTerrainRegistration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TextMasks.installFloatMask( txtTerrainArea );
        this.controller = new TerrainRegistrationController(this);
    }

    
    public void showError(String message, String errorType){
        lblErrorMessage.setText(message);
        lblErrorMessage.setVisible(true);
        BlinkText.blinkLabelRed(lblErrorMessage, 3);
        
        switch( errorType ){
            case "name" -> BlinkText.blinkTextFieldRed(txtTerrainName, 3);
            case "area" -> BlinkText.blinkTextFieldRed(txtTerrainArea, 3);
            case "location" -> BlinkText.blinkTextFieldRed(txtTerrainLocation, 3);
            case "" -> {}
            default -> System.out.println("Unknown error type: " + errorType);
        }
    }
    
    
    public void hideErrorMessage(){
        lblErrorMessage.setVisible(false);
    }
    
    
    public void clearForm(){
        txtTerrainName.setText("");
        txtOwnerCPF.setText("");
        txtTerrainArea.setText("");
        txtTerrainLocation.setText("");
        hideErrorMessage();
    }
    
    public String getTerrainNameText(){
        return txtTerrainName.getText();
    }
    
    
    public String getTerrainAreaText(){
        return txtTerrainArea.getText();
    }
    
    
    public String getTerrainLocationText(){
        return txtTerrainLocation.getText();
    }
    
    
    public void setOwnerName(String name){
        txtOwnerCPF.setText(name);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTerrainName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOwnerCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTerrainLocation = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnFindOwner = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();
        txtTerrainArea = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome do terreno");

        txtTerrainName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerrainNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Proprietário (CPF)");

        txtOwnerCPF.setEditable(false);
        txtOwnerCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerCPFActionPerformed(evt);
            }
        });

        jLabel3.setText("Área do terreno (m²)");

        jLabel4.setText("Localização");

        txtTerrainLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerrainLocationActionPerformed(evt);
            }
        });

        btnRegister.setText("Cadastrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnClose.setText("Fechar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnFindOwner.setText("Procurar");
        btnFindOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindOwnerActionPerformed(evt);
            }
        });

        lblErrorMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorMessage.setText("ERROR_MESSAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTerrainArea)
                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTerrainName)
                    .addComponent(txtTerrainLocation)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 245, Short.MAX_VALUE)
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegister))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtOwnerCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindOwner))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTerrainName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOwnerCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindOwner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTerrainArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTerrainLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtOwnerCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerCPFActionPerformed

    
    private void txtTerrainNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerrainNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerrainNameActionPerformed

    
    
    private void txtTerrainLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerrainLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerrainLocationActionPerformed

    
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed


    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        controller.handleSubmit();
    }//GEN-LAST:event_btnRegisterActionPerformed

    
    private void btnFindOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindOwnerActionPerformed
        controller.handleSearchOwner();
    }//GEN-LAST:event_btnFindOwnerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnFindOwner;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JTextField txtOwnerCPF;
    private javax.swing.JFormattedTextField txtTerrainArea;
    private javax.swing.JTextField txtTerrainLocation;
    private javax.swing.JTextField txtTerrainName;
    // End of variables declaration//GEN-END:variables
}
